In [1]:
import pandas as pd

df = pd.read_csv("/Users/anisa/OneDrive/Desktop/fyp/data/cleaned/done.csv")

In [2]:
df.shape

(12045, 5)

In [3]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [4]:
df.dtypes

geography                 object
stratum                   object
date              datetime64[ns]
organism                  object
resistance_pct           float64
dtype: object

In [5]:
print(df['date'])

0       2020-10-01
1       2020-11-01
2       2020-12-01
3       2021-01-01
4       2021-02-01
           ...
12040   2025-02-01
12041   2025-03-01
12042   2025-04-01
12043   2025-05-01
12044   2025-06-01
Name: date, Length: 12045, dtype: datetime64[ns]

In [6]:
df['date'].isna().sum()

np.int64(0)

In [7]:
df = df.sort_values(
    ["geography", "stratum", "organism", "date"]
)

In [8]:
df["geography"].value_counts()

geography
East of England         1339
West Midlands           1339
London                  1339
North West              1339
South East              1339
Yorkshire and Humber    1339
South West              1339
East Midlands           1337
North East              1335
Name: count, dtype: int64

In [9]:
df.groupby(
    ["geography", "stratum", "organism"]
)["date"].count().describe()

count    207.000000
mean      58.188406
std        0.979529
min       57.000000
25%       57.000000
50%       59.000000
75%       59.000000
max       59.000000
Name: date, dtype: float64

Forecast horizon - 6 months
Window Length - 12 months
Static features - (Organism,Antibiotic, region)
Dynamic features - Resistance history over time

Baseline/Benchmark - Linear regression

In [10]:
df["series_id"] = (
    df["organism"].astype(str)
    + "__" + df["stratum"].astype(str)
    + "__" + df["geography"].astype(str)
)

In [11]:
df.groupby(["series_id", "date"]).size().sort_values(ascending=False).head(20)

series_id                                       date
e-faecium__Glycopeptides__Yorkshire and Humber  2025-06-01    1
E-coli__Amikacin__East Midlands                 2020-10-01    1
                                                2020-11-01    1
                                                2020-12-01    1
                                                2021-01-01    1
                                                2021-02-01    1
                                                2021-03-01    1
                                                2021-04-01    1
                                                2021-05-01    1
                                                2021-06-01    1
                                                2021-07-01    1
                                                2021-08-01    1
                                                2021-09-01    1
e-faecium__Glycopeptides__Yorkshire and Humber  2024-02-01    1
                                                2024-01-01    1
                                                2023-12-01    1
                                                2023-11-01    1
                                                2023-10-01    1
                                                2023-09-01    1
                                                2023-08-01    1
dtype: int64

In [12]:
df = df.sort_values(["series_id", "date"])

In [13]:
df["series_id"].tail()

12040    e-faecium__Glycopeptides__Yorkshire and Humber
12041    e-faecium__Glycopeptides__Yorkshire and Humber
12042    e-faecium__Glycopeptides__Yorkshire and Humber
12043    e-faecium__Glycopeptides__Yorkshire and Humber
12044    e-faecium__Glycopeptides__Yorkshire and Humber
Name: series_id, dtype: object

In [14]:
df.head()

,geography,stratum,date,organism,resistance_pct,series_id
0,East Midlands,Amikacin,2020-10-01,E-coli,0.53,E-coli__Amikacin__East Midlands
1,East Midlands,Amikacin,2020-11-01,E-coli,0.92,E-coli__Amikacin__East Midlands
2,East Midlands,Amikacin,2020-12-01,E-coli,0.93,E-coli__Amikacin__East Midlands
3,East Midlands,Amikacin,2021-01-01,E-coli,0.53,E-coli__Amikacin__East Midlands
4,East Midlands,Amikacin,2021-02-01,E-coli,0.17,E-coli__Amikacin__East Midlands

In [15]:
y = (
    df.set_index(["series_id", "date"])
    ["resistance_pct"]
)

In [16]:
region_map = {
    "East Midlands": "Midlands",
    "West Midlands": "Midlands",
    "North East": "North East and Yorkshire",
    "Yorkshire and Humber": "North East and Yorkshire"
}

In [17]:
df["model_region"] = df["geography"].replace(region_map)

In [18]:
import glob
import os

base_path = "/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata"
files = glob.glob(os.path.join(base_path, "*.csv"))

Prescribing Data Cleaning

In [19]:
files

['/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\eastofengland.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\london.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\midlands.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\north east and york.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\north west.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\south east.csv',
 '/Users/anisa/OneDrive/Desktop/fyp/data/raw/prescribingdata\\south west.csv']

In [20]:

prescribing_list = []
for f in files :
    file = pd.read_csv(f)
    prescribing_list.append(file)
prescribing = pd.concat(prescribing_list, ignore_index=True)

In [21]:
prescribing["Area Type"].value_counts()
#prescribing["Area Name"].value_counts().head(20)

Area Type
ICB sub-locations    19758
England               1494
NHS regions           1482
Name: count, dtype: int64

In [22]:
prescribing_nhs = prescribing[
    prescribing["Area Type"] == "NHS regions"
].copy()

In [23]:
prescribing_nhs["Area Name"].unique()

array(['East of England NHS Region', 'London NHS Region',
       'Midlands NHS Region', 'North East and Yorkshire NHS Region',
       'North West NHS Region', 'South East NHS Region',
       'South West NHS Region'], dtype=object)

In [24]:
prescribing_region_map = {
    "Midlands NHS Region": "Midlands",
    "North East and Yorkshire NHS region" : "North East and Yorkshire",
    "South West NHS Region": "South West",
    "South East NHS Region": "South East",
    "London NHS Region": "London",
    "East of England NHS Region": "East of England",
    "North West NHS Region": "North West"
}

In [25]:
prescribing_nhs["model_region"] = prescribing_nhs["Area Name"].replace(
    prescribing_region_map
)

In [26]:
prescribing_nhs["model_region"].isna().sum()

np.int64(0)

In [27]:
prescribing_nhs.head()

,Indicator ID,Indicator Name,Parent Code,Parent Name,Area Code,Area Name,Area Type,Sex,Age,Category Type,...,Denominator,Value note,Recent Trend,Compared to England value or percentiles,Compared to NHS regions value or percentiles,Time period Sortable,New data,Compared to goal,Time period range,model_region
1,92344,Twelve-month rolling total number of prescribe...,E92000001,England,E40000007,East of England NHS Region,NHS regions,Persons,All ages,NaN,...,3536917.0,Aggregated from all known lower geography values,NaN,Not compared,Not compared,20140001,NaN,NaN,1m,East of England
14,92344,Twelve-month rolling total number of prescribe...,E92000001,England,E40000007,East of England NHS Region,NHS regions,Persons,All ages,NaN,...,3536917.0,Aggregated from all known lower geography values,NaN,Not compared,Not compared,20140002,NaN,NaN,1m,East of England
27,92344,Twelve-month rolling total number of prescribe...,E92000001,England,E40000007,East of England NHS Region,NHS regions,Persons,All ages,NaN,...,3536917.0,Aggregated from all known lower geography values,NaN,Not compared,Not compared,20140003,NaN,NaN,1m,East of England
40,92344,Twelve-month rolling total number of prescribe...,E92000001,England,E40000007,East of England NHS Region,NHS regions,Persons,All ages,NaN,...,3536917.0,Aggregated from all known lower geography values,NaN,Not compared,Not compared,20140004,NaN,NaN,1m,East of England
53,92344,Twelve-month rolling total number of prescribe...,E92000001,England,E40000007,East of England NHS Region,NHS regions,Persons,All ages,NaN,...,3536917.0,Aggregated from all known lower geography values,NaN,Not compared,Not compared,20140005,NaN,NaN,1m,East of England

In [28]:
prescribing_nhs["Time period"].head(10)

1      Jan-14
14     Feb-14
27     Mar-14
40     Apr-14
53     May-14
66     Jun-14
79     Jul-14
92     Aug-14
105    Sep-14
118    Oct-14
Name: Time period, dtype: object

In [29]:
prescribing_nhs["Time period"].value_counts().head(10)

Time period
May-15    10
Jun-15    10
Jul-15    10
Aug-15    10
Jan-15    10
Feb-15    10
Mar-15    10
Apr-15    10
Sep-15    10
Oct-15    10
Name: count, dtype: int64

In [30]:
monthly = prescribing_nhs[
    prescribing_nhs["Time period"].str.match(r"^[A-Za-z]{3}-\d{2}$", na=False)
].copy()

In [31]:
monthly["date"] = pd.to_datetime(
    monthly["Time period"],
    format="%b-%y"
)

In [32]:
prescribing_clean = monthly[
    [
        "Area Name",
        "date",
        "Value"
    ]
].rename(columns={
    "Area Name": "model_region",
    "Value": "prescribing_rate"
})

In [33]:
prescribing_clean.dtypes

model_region                object
date                datetime64[ns]
prescribing_rate           float64
dtype: object

In [34]:
print("Prescribing regions: ")
print(prescribing_clean["model_region"].unique())

print("\nAMR regions: ")
print(df["model_region"].unique())

Prescribing regions:
['East of England NHS Region' 'London NHS Region' 'Midlands NHS Region'
 'North East and Yorkshire NHS Region' 'North West NHS Region'
 'South East NHS Region' 'South West NHS Region']

AMR regions:
['Midlands' 'East of England' 'London' 'North East and Yorkshire'
 'North West' 'South East' 'South West']

In [35]:
df.head()

,geography,stratum,date,organism,resistance_pct,series_id,model_region
0,East Midlands,Amikacin,2020-10-01,E-coli,0.53,E-coli__Amikacin__East Midlands,Midlands
1,East Midlands,Amikacin,2020-11-01,E-coli,0.92,E-coli__Amikacin__East Midlands,Midlands
2,East Midlands,Amikacin,2020-12-01,E-coli,0.93,E-coli__Amikacin__East Midlands,Midlands
3,East Midlands,Amikacin,2021-01-01,E-coli,0.53,E-coli__Amikacin__East Midlands,Midlands
4,East Midlands,Amikacin,2021-02-01,E-coli,0.17,E-coli__Amikacin__East Midlands,Midlands

In [36]:
prescribing_clean.head()

                  model_region       date  prescribing_rate
1   East of England NHS Region 2014-01-01          1.925150
14  East of England NHS Region 2014-02-01          1.916657
27  East of England NHS Region 2014-03-01          1.919446
40  East of England NHS Region 2014-04-01          1.918850
53  East of England NHS Region 2014-05-01          1.924075

In [37]:
region_map = {
    "East of England NHS Region": "East of England",
    "Midlands NHS Region":"Midlands",
    "London NHS Region": "London",
    "North East and Yorkshire NHS Region":"North East and Yorkshire",
    "North West NHS Region": "North West",
    "South East NHS Region": "South East",
    "South West NHS Region": "South West"
}

In [38]:
prescribing_clean["region"] = (
    prescribing_clean["model_region"]
    .map(region_map)
)

In [39]:
prescribing_clean.head()

                  model_region       date  prescribing_rate           region
1   East of England NHS Region 2014-01-01          1.925150  East of England
14  East of England NHS Region 2014-02-01          1.916657  East of England
27  East of England NHS Region 2014-03-01          1.919446  East of England
40  East of England NHS Region 2014-04-01          1.918850  East of England
53  East of England NHS Region 2014-05-01          1.924075  East of England

In [40]:
prescribing_clean["region"].value_counts(dropna=False)

region
South East                  528
Midlands                    138
East of England             138
North West                  138
North East and Yorkshire    138
South West                  138
London                      126
Name: count, dtype: int64

In [41]:
prescribing_clean = prescribing_clean.rename(
    columns={"region": "model_region"}
)

In [42]:

prescribing_clean.columns = [
    "model_region_nhs",
    "date",
    "prescribing_rate",
    "model_region"
]

In [43]:
prescribing_clean = prescribing_clean.drop(columns=["model_region_nhs"])

In [44]:
prescribing_clean.head()

         date  prescribing_rate     model_region
1  2014-01-01          1.925150  East of England
14 2014-02-01          1.916657  East of England
27 2014-03-01          1.919446  East of England
40 2014-04-01          1.918850  East of England
53 2014-05-01          1.924075  East of England

In [45]:
df.info

<bound method DataFrame.info of                   geography        stratum       date   organism  \
0             East Midlands       Amikacin 2020-10-01     E-coli
1             East Midlands       Amikacin 2020-11-01     E-coli
2             East Midlands       Amikacin 2020-12-01     E-coli
3             East Midlands       Amikacin 2021-01-01     E-coli
4             East Midlands       Amikacin 2021-02-01     E-coli
...                     ...            ...        ...        ...
12040  Yorkshire and Humber  Glycopeptides 2025-02-01  e-faecium
12041  Yorkshire and Humber  Glycopeptides 2025-03-01  e-faecium
12042  Yorkshire and Humber  Glycopeptides 2025-04-01  e-faecium
12043  Yorkshire and Humber  Glycopeptides 2025-05-01  e-faecium
12044  Yorkshire and Humber  Glycopeptides 2025-06-01  e-faecium

       resistance_pct                                       series_id  \
0                0.53                 E-coli__Amikacin__East Midlands
1                0.92                 E-coli__Amikacin__East Midlands
2                0.93                 E-coli__Amikacin__East Midlands
3                0.53                 E-coli__Amikacin__East Midlands
4                0.17                 E-coli__Amikacin__East Midlands
...               ...                                             ...
12040           14.85  e-faecium__Glycopeptides__Yorkshire and Humber
12041           20.45  e-faecium__Glycopeptides__Yorkshire and Humber
12042           21.74  e-faecium__Glycopeptides__Yorkshire and Humber
12043           25.47  e-faecium__Glycopeptides__Yorkshire and Humber
12044           21.05  e-faecium__Glycopeptides__Yorkshire and Humber

                   model_region
0                      Midlands
1                      Midlands
2                      Midlands
3                      Midlands
4                      Midlands
...                         ...
12040  North East and Yorkshire
12041  North East and Yorkshire
12042  North East and Yorkshire
12043  North East and Yorkshire
12044  North East and Yorkshire

[12045 rows x 7 columns]>

Merge AMR and Prescribing Datasets

In [46]:
prescribing_clean.duplicated(
    ["model_region", "date"]
).sum()

np.int64(390)

In [47]:
prescribing_agg = (
    prescribing_clean
    .groupby(["model_region", "date"], as_index=False)
    .agg({"prescribing_rate": "mean"})
)

In [48]:
prescribing_agg.to_csv("prescribingdata.csv")

In [49]:
df = df.sort_values(["model_region", "date"])
prescribing_agg = prescribing_agg.sort_values(["model_region", "date"])

combined_df = df.merge(
    prescribing_agg,
    on=["model_region", "date"],
    how="left"
)

In [50]:
combined_df.to_csv("datab.csv")

In [51]:
combined_df.info

<bound method DataFrame.info of              geography                       stratum       date      organism  \
0      East of England                      Amikacin 2020-08-01  K-pneumoniae
1      East of England                   Carbapenems 2020-08-01  K-pneumoniae
2      East of England                 Ciprofloxacin 2020-08-01  K-pneumoniae
3      East of England                  Co-amoxiclav 2020-08-01  K-pneumoniae
4      East of England                    Gentamicin 2020-08-01  K-pneumoniae
...                ...                           ...        ...           ...
12040       South West  Piperacillin with tazobactam 2025-06-01  P-aeruginosa
12041       South West                    Macrolides 2025-06-01  S-pneumoniae
12042       South West                    Penicillin 2025-06-01  S-pneumoniae
12043       South West                 Glycopeptides 2025-06-01    e-faecalis
12044       South West                 Glycopeptides 2025-06-01     e-faecium

       resistance_pct                                          series_id  \
0                0.64            K-pneumoniae__Amikacin__East of England
1                0.00         K-pneumoniae__Carbapenems__East of England
2               11.06       K-pneumoniae__Ciprofloxacin__East of England
3               27.04        K-pneumoniae__Co-amoxiclav__East of England
4                4.90          K-pneumoniae__Gentamicin__East of England
...               ...                                                ...
12040            4.35  P-aeruginosa__Piperacillin with tazobactam__So...
12041            6.78               S-pneumoniae__Macrolides__South West
12042            1.02               S-pneumoniae__Penicillin__South West
12043            3.64              e-faecalis__Glycopeptides__South West
12044           27.17               e-faecium__Glycopeptides__South West

          model_region  prescribing_rate
0      East of England              1.52
1      East of England              1.52
2      East of England              1.52
3      East of England              1.52
4      East of England              1.52
...                ...               ...
12040       South West              1.35
12041       South West              1.35
12042       South West              1.35
12043       South West              1.35
12044       South West              1.35

[12045 rows x 8 columns]>

In [52]:
combined_df.head()

,geography,stratum,date,organism,resistance_pct,series_id,model_region,prescribing_rate
0,East of England,Amikacin,2020-08-01,K-pneumoniae,0.64,K-pneumoniae__Amikacin__East of England,East of England,1.52
1,East of England,Carbapenems,2020-08-01,K-pneumoniae,0.00,K-pneumoniae__Carbapenems__East of England,East of England,1.52
2,East of England,Ciprofloxacin,2020-08-01,K-pneumoniae,11.06,K-pneumoniae__Ciprofloxacin__East of England,East of England,1.52
3,East of England,Co-amoxiclav,2020-08-01,K-pneumoniae,27.04,K-pneumoniae__Co-amoxiclav__East of England,East of England,1.52
4,East of England,Gentamicin,2020-08-01,K-pneumoniae,4.90,K-pneumoniae__Gentamicin__East of England,East of England,1.52

In [53]:
combined_df["date"] = pd.to_datetime(combined_df["date"]) 
combined_df = combined_df.sort_values(["series_id", "date"]).reset_index(drop=True)

In [54]:
combined_df["month"] = combined_df["date"].dt.month

In [56]:
len(combined_df)

12045

In [57]:
combined_df.to_csv("/Users/anisa/OneDrive/Desktop/fyp/notebooks/datab_original.csv")